name: hundred_pay_hq_wrapper
description: A simple Dart/Flutter wrapper for the 100pay API to verify payments, preview conversions, and create sub-accounts.
version: 0.0.2
homepage: https://github.com/shop100global/hundred_pay_dart_wrapper
repository: https://github.com/shop100global/hundred_pay_dart_wrapper
issue_tracker: https://github.com/shop100global/hundred_pay_dart_wrapper/issues
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  http: ^1.3.0
  collection: ^1.18.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
